description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Mulish"
      fonts: 
        - 
          asset: "fonts/Mulish-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "fonts/Mulish-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Mulish-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Aleo"
      fonts: 
        - 
          asset: "fonts/Aleo-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Amiri"
      fonts: 
        - 
          asset: "fonts/Amiri-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Amiri-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
