import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedPOSTRESYCAFEWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$80Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$100Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedGroupWidget11.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedCakeWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$90Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedGroupWidget14.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$50Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedCanelitaWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedAkariconscircleplusWidget1.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedAkariconscircleplusWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedKittyWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$45Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedGroupWidget10.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedSusancervantesnro11Widget3.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedMenuinferiorWidget3.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedGroupWidget12.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedGroupWidget13.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedTomNookWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/Generated\$70Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedTotakekeWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedBARRAWidget2.dart';
import 'package:flutterapp/actcafeinternetapp/generatedmenuwidget6/generated/GeneratedBaabaraWidget.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 67.0,
                child: GeneratedBARRAWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 48.0,
                child: GeneratedPOSTRESYCAFEWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 75.66667175292969,
                child: GeneratedCanelitaWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 79.33333587646484,
                child: GeneratedBaabaraWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 85.0,
                child: GeneratedCakeWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 71.66667175292969,
                child: GeneratedTotakekeWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 74.16666412353516,
                child: GeneratedTomNookWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 70.0,
                child: GeneratedKittyWidget(),
              ),
              Positioned(
                left: 354.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconscircleplusWidget(),
              ),
              Positioned(
                left: 356.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroupWidget10(),
              ),
              Positioned(
                left: 362.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconscircleplusWidget1(),
              ),
              Positioned(
                left: 358.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroupWidget11(),
              ),
              Positioned(
                left: 356.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroupWidget12(),
              ),
              Positioned(
                left: 360.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroupWidget13(),
              ),
              Positioned(
                left: 357.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroupWidget14(),
              ),
              Positioned(
                left: 296.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$70Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$80Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$100Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$50Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$90Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 770.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 43.0,
                child: Generated$45Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 29.0,
                child: GeneratedSusancervantesnro11Widget3(),
              )
            ]),
      ),
    ));
  }
}
