import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedMesWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedAoWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedDiaWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedMenuinferiorWidget2.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedHoraWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedCalendario1Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedSusancervantesnro11Widget2.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedAGENDARCITAWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedBARRAWidget1.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaswidget4/generated/GeneratedRectangle10Widget.dart';

/* Frame Citas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCitasWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 67.0,
                child: GeneratedBARRAWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 505.0,
                child: GeneratedCalendario1Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 50.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 50.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 50.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 50.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 27.0,
                child: GeneratedDiaWidget(),
              ),
              Positioned(
                left: 282.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 27.0,
                child: GeneratedMesWidget(),
              ),
              Positioned(
                left: 283.0,
                top: 361.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 27.0,
                child: GeneratedAoWidget(),
              ),
              Positioned(
                left: 286.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 27.0,
                child: GeneratedHoraWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 68.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 25.0,
                child: GeneratedAGENDARCITAWidget(),
              ),
              Positioned(
                left: 276.0,
                top: 801.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 29.0,
                child: GeneratedSusancervantesnro11Widget2(),
              )
            ]),
      ),
    ));
  }
}
