import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedBARRAWidget5.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedRegresarWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedMenuinferiorWidget6.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedcitaagendadawidget/generated/GeneratedSucitahasidoagendadaconexitoWidget.dart';

/* Frame citaagendada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCitaagendadaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 67.0,
                child: GeneratedBARRAWidget5(),
              ),
              Positioned(
                left: 42.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 135.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 62.0,
                child: GeneratedSucitahasidoagendadaconexitoWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 68.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 702.0,
                right: null,
                bottom: null,
                width: 101.0,
                height: 35.0,
                child: GeneratedRegresarWidget(),
              )
            ]),
      ),
    ));
  }
}
