import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget11/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget11/generated/GeneratedBARRAWidget4.dart';

/* Frame Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClienteWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 67.0,
                child: GeneratedBARRAWidget4(),
              )
            ]),
      ),
    ));
  }
}
