import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedBARRAWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedAPARTATUCITAYA3Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedYaabrimosnuestroCafeInternetinspiradoenelvideojuegodeWi.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedSusancervantesnro11Widget1.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedZ_8HVWXyV8Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedMenuinferiorWidget1.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedVisitanuestrasinstalacionesconcitapreviaparateneracceso.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedAnimalCrossingCafeWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatediniciowidget1/generated/GeneratedAc1Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 896.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 896.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 252, 243, 161),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 821.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 75.0,
                              child: GeneratedMenuinferiorWidget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 343.0,
                              right: null,
                              bottom: null,
                              width: 388.0,
                              height: 70.0,
                              child:
                                  GeneratedYaabrimosnuestroCafeInternetinspiradoenelvideojuegodeWi(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 134.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 55.0,
                              child: GeneratedAnimalCrossingCafeWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 256.0,
                              height: 177.0,
                              child:
                                  GeneratedVisitanuestrasinstalacionesconcitapreviaparateneracceso(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 794.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 29.0,
                              child: GeneratedAPARTATUCITAYA3Widget(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 605.0,
                              right: null,
                              bottom: null,
                              width: 97.0,
                              height: 176.0,
                              child: GeneratedAc1Widget(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 87.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 243.0,
                              child: GeneratedZ_8HVWXyV8Widget(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 67.0,
                              child: GeneratedBARRAWidget(),
                            ),
                            Positioned(
                              left: 276.0,
                              top: 802.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 29.0,
                              child: GeneratedSusancervantesnro11Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
