import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedinputwidget3/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/actcafeinternetapp/generatedinputwidget3/generated/GeneratedIngresatucorreoWidget3.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 60.0,
              child: GeneratedRectangle2Widget3(),
            ),
            Positioned(
              left: 16.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 125.0,
              height: 22.0,
              child: GeneratedIngresatucorreoWidget3(),
            )
          ]),
    ));
  }
}
