import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedSusancervantesnro11Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedMaskGroupWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedIngresatuinformacionWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedBienvenidodevueltaWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/actcafeinternetapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: -26.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 511.0,
                height: 441.0,
                child: GeneratedMaskGroupWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 795.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 30.0,
                child: GeneratedIngresatuinformacionWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 37.0,
                child: GeneratedBienvenidodevueltaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget2(),
              ),
              Positioned(
                left: 44.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 30.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 182.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 29.0,
                child: GeneratedSusancervantesnro11Widget(),
              )
            ]),
      ),
    ));
  }
}
