import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedDatospersonalesWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedEDITARWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedBxbxcheckcircleWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedApellidoMaternoWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedHolaWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedApellidopaternoWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedAkariconslocationWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedSusancervantesnro11Widget4.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedMenuinferiorWidget4.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedCorreoWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedSucursalesWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedNuevaZelanda7870Oasis32697CdJurezChihWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedSUCURSALWidget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/actcafeinternetapp/generatedclientewidget8/generated/GeneratedBARRAWidget3.dart';

/* Frame Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClienteWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 252, 243, 161),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 821.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 75.0,
                child: GeneratedMenuinferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 67.0,
                child: GeneratedBARRAWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 66.0,
                child: GeneratedHolaWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 43.0,
                child: GeneratedDatospersonalesWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 25.0,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 25.0,
                child: GeneratedCorreoWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 22.0,
                child: GeneratedApellidopaternoWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 45.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 93.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 22.0,
                child: GeneratedApellidoMaternoWidget(),
              ),
              Positioned(
                left: 189.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 25.0,
                child: GeneratedEDITARWidget(),
              ),
              Positioned(
                left: -182.0,
                top: 880.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 40.0,
                child: GeneratedSucursalesWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedAkariconslocationWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 65.0,
                child: GeneratedNuevaZelanda7870Oasis32697CdJurezChihWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 37.0,
                child: GeneratedSUCURSALWidget(),
              ),
              Positioned(
                left: 341.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 34.0,
                child: GeneratedBxbxcheckcircleWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 29.0,
                child: GeneratedSusancervantesnro11Widget4(),
              )
            ]),
      ),
    ));
  }
}
