import 'package:flutter/material.dart';
import 'package:flutterapp/actcafeinternetapp/generatedfluentsettings16regularwidget/generated/GeneratedGroupWidget24.dart';

/* Frame fluent:settings-16-regular
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFluentsettings16regularWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 16.0,
        height: 16.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 2.249769926071167,
                top: 2.000936269760132,
                right: null,
                bottom: null,
                width: 11.501460075378418,
                height: 11.997166633605957,
                child: GeneratedGroupWidget24(),
              )
            ]),
      ),
    ));
  }
}
